services:
  api:
    build: drenoday
    container_name: drenoday
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drenoday.rule=Host(`drenoday.enor.tech`)"
      - "traefik.http.routers.drenoday.entrypoints=websecure"
      - "traefik.http.routers.drenoday.tls.certresolver=myresolver"
      - "traefik.http.services.drenoday.loadbalancer.server.port=3000"
    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/deploy:/home/deploy


networks:
  traefik-network:
    external: true
