services:
  api:
    build: .
    container_name: drenoday
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drenoday.rule=Host(`drenoday.enor.tech`)"
      - "traefik.http.routers.drenoday.entrypoints=websecure"
      - "traefik.http.routers.drenoday.tls.certresolver=myresolver"
      - "traefik.http.services.drenoday.loadbalancer.server.port=3000"
    networks:
      - traefik-network  # Connect to the Traefik network

networks:
  traefik-network:
    external: true
